In [8]:
import numpy as np

In [ ]:
a =  np.empty((2,3))

In [9]:
a[0]=0

In [10]:
a

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [7.56577399e-307, 9.34600963e-307, 1.00136896e-307]])

In [11]:
a[1]=1


In [12]:
a

array([[0., 0., 0.],
       [1., 1., 1.]])

In [13]:
a = np.arange(5)

In [14]:
a

array([0, 1, 2, 3, 4])

In [15]:
points = np.arange(-1,1,0.5)

In [16]:
 xs, ys = np.meshgrid(points, points)

In [17]:
 xs

array([[-1. , -0.5,  0. ,  0.5],
       [-1. , -0.5,  0. ,  0.5],
       [-1. , -0.5,  0. ,  0.5],
       [-1. , -0.5,  0. ,  0.5]])

In [18]:
points

array([-1. , -0.5,  0. ,  0.5])

In [1]:
import numpy as np


In [16]:
a =np.random.randint(0,2,size=(2,3))

In [17]:
a

array([[0, 0, 1],
       [1, 1, 0]])

In [20]:
b=np.where(a>0,1,0)

In [21]:
b

array([[0, 0, 1],
       [1, 1, 0]])

In [23]:
c=b.cumsum()

In [24]:
c

array([0, 0, 1, 2, 3, 3], dtype=int32)

In [26]:
type(c)

numpy.ndarray